### ISSUE TITLE
关于gector模型的效果对比

### ISSUE THREAD

**Issue by uloveqian2021** [xueyouluo/speller-bert#2]
大佬有做过关于gector模型跟其他模型的效果对比吗

**Comment by xueyouluo** [comment]
简单对比过与cbert在1-1纠错上的效果，比较差，因为我训练的这版gector效果并不好，所以就没有做更多对比了。

**Comment by uloveqian2021** [comment]
> 简单对比过与cbert在1-1纠错上的效果，比较差，因为我训练的这版gector效果并不好，所以就没有做更多对比了。

大佬，我尝试训练模型，发现少了dimsim_confusion.json这个文件，您能提供一下吗

**Comment by xueyouluo** [comment]
那个是用dimsim找的音近词，效果一般般吧，你可以先注释掉用那个的地方，影响应该不大，我等下传一份上去。

**Comment by xueyouluo** [comment]
链接: https://pan.baidu.com/s/1_dKEIvH-9dAje5SOcfG1sQ  密码: fn7v

**Comment by uloveqian2021** [comment]
> 那个是用dimsim找的音近词，效果一般般吧，你可以先注释掉用那个的地方，影响应该不大，我等下传一份上去。

好的，感谢！
